"""empty message

Revision ID: 059866cf5fd1
Revises: f8ae7dce0740
Create Date: 2016-05-27 20:38:14.629924

"""

# revision identifiers, used by Alembic.
revision = '059866cf5fd1'
down_revision = 'f8ae7dce0740'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('hisemail', sa.String(length=120), nullable=True))
    op.add_column('Users', sa.Column('newattr', sa.Integer(), nullable=False))
    op.drop_index('email', table_name='Users')
    op.create_unique_constraint(None, 'Users', ['hisemail'])
    op.drop_column('Users', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'Users', type_='unique')
    op.create_index('email', 'Users', ['email'], unique=True)
    op.drop_column('Users', 'newattr')
    op.drop_column('Users', 'hisemail')
    ### end Alembic commands ###
