"""empty message

Revision ID: 05e70989b165
Revises: cfbf44a119e2
Create Date: 2016-05-31 22:14:45.879239

"""

# revision identifiers, used by Alembic.
revision = '05e70989b165'
down_revision = 'cfbf44a119e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gu_table',
    sa.Column('gu_id', sa.Integer(), nullable=False),
    sa.Column('ns_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ns_id'], ['ns_table.ns_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('gu_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gu_table')
    ### end Alembic commands ###
