"""initial migration

Revision ID: 07c3af72c051
Revises: None
Create Date: 2016-05-27 19:43:32.309095

"""

# revision identifiers, used by Alembic.
revision = '07c3af72c051'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('passwd_hash', sa.String(length=128), nullable=True))
    op.alter_column('Users', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("''"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("''"))
    op.drop_column('Users', 'passwd_hash')
    ### end Alembic commands ###
