"""empty message

Revision ID: 127e2adb60d2
Revises: 05e70989b165
Create Date: 2016-05-31 22:45:00.514387

"""

# revision identifiers, used by Alembic.
revision = '127e2adb60d2'
down_revision = '05e70989b165'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Messages')
    ### end Alembic commands ###
