"""empty message

Revision ID: 2e719737896d
Revises: 3f7ee71d9e74
Create Date: 2016-05-31 19:38:36.147252

"""

# revision identifiers, used by Alembic.
revision = '2e719737896d'
down_revision = '3f7ee71d9e74'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ns_table',
    sa.Column('ns_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=32), nullable=True),
    sa.Column('group_size', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('ns_id')
    )
    op.drop_table('Relationship')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Relationship',
    sa.Column('re_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('friend_a', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('friend_b', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['friend_a'], ['User.id'], name='relationship_ibfk_1'),
    sa.ForeignKeyConstraint(['friend_b'], ['User.id'], name='relationship_ibfk_2'),
    sa.PrimaryKeyConstraint('re_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('ns_table')
    ### end Alembic commands ###
