"""empty message

Revision ID: 973304c2bfa0
Revises: 059866cf5fd1
Create Date: 2016-05-27 20:39:41.276696

"""

# revision identifiers, used by Alembic.
revision = '973304c2bfa0'
down_revision = '059866cf5fd1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('email', sa.String(length=120), nullable=True))
    op.alter_column('Users', 'passwd_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('Users', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.drop_index('hisemail', table_name='Users')
    op.create_unique_constraint(None, 'Users', ['email'])
    op.drop_column('Users', 'newattr')
    op.drop_column('Users', 'hisemail')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('hisemail', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('Users', sa.Column('newattr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Users', type_='unique')
    op.create_index('hisemail', 'Users', ['hisemail'], unique=True)
    op.alter_column('Users', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('Users', 'passwd_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_column('Users', 'email')
    ### end Alembic commands ###
