"""empty message

Revision ID: 9f328e0f6013
Revises: e4e8caad13ca
Create Date: 2016-05-31 16:55:30.646980

"""

# revision identifiers, used by Alembic.
revision = '9f328e0f6013'
down_revision = 'e4e8caad13ca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('passwd_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('Nickname', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.drop_table('Users')
    op.add_column('Relationship', sa.Column('friend_a', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Relationship', 'User', ['friend_a'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Relationship', type_='foreignkey')
    op.drop_column('Relationship', 'friend_a')
    op.create_table('Users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('passwd_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('Nickname', mysql.VARCHAR(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    ### end Alembic commands ###
