"""empty message

Revision ID: cfbf44a119e2
Revises: 2e719737896d
Create Date: 2016-05-31 21:02:31.640442

"""

# revision identifiers, used by Alembic.
revision = 'cfbf44a119e2'
down_revision = '2e719737896d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Relationship',
    sa.Column('re_id', sa.Integer(), nullable=False),
    sa.Column('friend_a', sa.Integer(), nullable=True),
    sa.Column('friend_b', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_a'], ['User.id'], ),
    sa.ForeignKeyConstraint(['friend_b'], ['User.id'], ),
    sa.PrimaryKeyConstraint('re_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Relationship')
    ### end Alembic commands ###
