"""empty message

Revision ID: e4e8caad13ca
Revises: 973304c2bfa0
Create Date: 2016-05-31 16:54:16.255161

"""

# revision identifiers, used by Alembic.
revision = 'e4e8caad13ca'
down_revision = '973304c2bfa0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Relationship',
    sa.Column('re_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('re_id')
    )
    op.add_column('Users', sa.Column('Nickname', sa.String(length=12), nullable=True))
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.drop_index('email', table_name='Users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'Users', ['email'], unique=True)
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_column('Users', 'Nickname')
    op.drop_table('Relationship')
    ### end Alembic commands ###
